spring:
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update   # cria/atualiza as tabelas
    show-sql: true        # mostra as queries no console
    properties:
      hibernate:
        format_sql: true  # deixa o SQL bonitinho

  h2:
    console:
      enabled: true       # habilita o console web
      path: /h2-console   # endereço do console
